AllCops:
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
    - bin/*
Rails:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/MethodLength:
  Exclude:
    - db/migrate/*
